#include <stdio.h>
#include <string.h>
void buildTable(char charTable[])
{
	memset(charTable, 0, 127);
	//                  ABCDEFG
	charTable['!'] = 0b01001001; 
	charTable[' '] = 0b00000000;  
	charTable['0'] = 0b01111110; 
	charTable['1'] = 0b00110000; 
	charTable['2'] = 0b01101101; 
	charTable['3'] = 0b01111001; 
	charTable['4'] = 0b00110011; 
	charTable['5'] = 0b01011011; 
	charTable['6'] = 0b01011111; 
	charTable['7'] = 0b01110000; 
	charTable['8'] = 0b01111111;  
	charTable['9'] = 0b01111011;  
	charTable['A'] = 0b01110111;  
	charTable['a'] = 0b01111101;  
	charTable['B'] = 0b00011111;  
	charTable['b'] = 0b00011111;  
	charTable['C'] = 0b01001110;  
	charTable['c'] = 0b00001101;  
	charTable['D'] = 0b00111101;  
	charTable['d'] = 0b00111101;  
	charTable['E'] = 0b01001111;  
	charTable['e'] = 0b01101111;  
	charTable['F'] = 0b01000111;  
	charTable['f'] = 0b01000111;  
	charTable['G'] = 0b01011110;  
	charTable['g'] = 0b01111011;  
	charTable['H'] = 0b00110111;  
	charTable['h'] = 0b00010111;  
	charTable['I'] = 0b00000110;  
	charTable['i'] = 0b00000110;  
	charTable['J'] = 0b00111000;  
	charTable['j'] = 0b00011000;  
	charTable['K'] = 0b00110111;  
	charTable['k'] = 0b00110111;  
	charTable['L'] = 0b00001110;  
	charTable['l'] = 0b00001110;  
	charTable['M'] = 0b01010101;  
	charTable['m'] = 0b01010101;  
	charTable['N'] = 0b00010101;  
	charTable['n'] = 0b00010101;  
	charTable['O'] = 0b01111110;  
	charTable['o'] = 0b00011101;  
	charTable['P'] = 0b01100111;  
	charTable['p'] = 0b01100111;  
	charTable['Q'] = 0b01110011;  
	charTable['q'] = 0b01110011;  
	charTable['R'] = 0b00000101;  
	charTable['r'] = 0b00000101;  
	charTable['S'] = 0b01011011;  
	charTable['s'] = 0b01011011;  
	charTable['T'] = 0b00001111;  
	charTable['t'] = 0b00001111;  
	charTable['U'] = 0b00111110;  
	charTable['u'] = 0b00011100;  
	charTable['V'] = 0b00111110;  
	charTable['v'] = 0b00111110;  
	charTable['W'] = 0b00111111;  
	charTable['w'] = 0b00111111;  
	charTable['X'] = 0b00110111;  
	charTable['x'] = 0b00110111;  
	charTable['Y'] = 0b00111011;  
	charTable['y'] = 0b00111011;  
	charTable['Z'] = 0b01101101;  
	charTable['z'] = 0b01101101;  
	charTable['('] = 0b01001110;  
	charTable['['] = 0b01001110;  
	charTable['-'] = 0b00000001;  
	charTable['.'] = 0b10000000;  // dot led on!
	charTable['*'] = 0b01100011;  
	charTable['_'] = 0b00001000;  
	charTable['='] = 0b00001001;  
	charTable['?'] = 0b01100101;  
	charTable['^'] = 0b01000000;  
	charTable[')'] = 0b01111000;  
	charTable[']'] = 0b01111000;  
	charTable['@'] = 0b01110101;  
	charTable['/'] = 0b00100101;  
	charTable['\\'] =0b00010011;  
	charTable[':'] = 0b00110110;  
	charTable['"'] = 0b00100010;  
	charTable['\''] =0b00100000; 
	//                  ABCDEFG
}

void printBinary(char *s, int n) 
{
    for(int i = 0; i < 8; i++) 
    {
        int bit = (n >> i) & 1;
        s[7-i] = bit+'0';
    }
}

void to_char(int n, char *str)
{
    if (n < 32 || n > 127) 
        sprintf(str, "\\%i", n);
    else
        sprintf(str, "'%c'", n);
}
int main()
{
    char charTable[127];
    buildTable(charTable);
    FILE *fp = fopen("../src/charTable.h", "w+");
    if(fp == NULL)
    {
        printf("Error opening file!\n");
        return 1;
    }

    fprintf(fp, "// This file is generated by genTable.c\n");
    fprintf(fp, "// DO NOT EDIT\n\n");
    fprintf(fp, "static const unsigned char charTable[127] PROGMEM = {\n");
    char bi[9], str[10];
    bi[8] = '\0';
    for(int i = 0; i < 127; i++)
    {
        printBinary(bi, charTable[i]);
        to_char(i, str);
        fprintf(fp, "0b%s,  // %s\n", bi, str);
    }
    fprintf(fp, "\n};\n");
    fclose(fp); 
    printf("charTable.h generated successfully!\n");
    return 0;
}
